Refactor if ale customizing zo abstract class
abap-observability-tools/abap-log-exporter pull request #39
Opened 2020-10-29 13:24 UTC by Goala

https://github.com/Goala/abap-log-exporter/issues/30

2020-10-29 18:00 UTC, JohannesKonings requested changes
see comments

2020-10-29 18:00 UTC, JohannesKonings commented on src/zcl_ale_customizing.clas.abap
> +      IMPORTING scenario TYPE zale_config-ale_scenario.
Could you change that to a constructor? Than it'll not forgotten to set the scenario.

2020-10-29 18:00 UTC, JohannesKonings commented on src/zcl_ale_customizing_base.clas.abap
> +  ENDMETHOD.
That should be in the abstract class, than it could be used for all inheriting classes.

2020-10-30 08:48 UTC, Goala commented on src/zcl_ale_customizing.clas.abap
> +      IMPORTING scenario TYPE zale_config-ale_scenario.
implemented

2020-10-30 08:48 UTC, Goala commented on src/zcl_ale_customizing_base.clas.abap
> +  ENDMETHOD.
implemented

2020-10-30 09:09 UTC, JohannesKonings approved these changes
LGTM

2020-10-30 09:10 UTC, merged